Handling for generic validation error
debezium/debezium-ui-poc pull request #280
Opened 2021-01-18 20:00 UTC by mdrillin

Addresses Issue #278 
- added handling for GenericValidationResults in CreateConnectorComponent
- some numeric inputs require positive int - added POS-INT type and sets a different min value for those on FormInputComponent
- fix issue in CreateConnectorComponent, was checking DataOptions instead of RuntimeOptions

2021-01-19 06:46 UTC, indraraj commented on ui/packages/ui/src/app/pages/createConnector/CreateConnectorComponent.tsx
> +            alert(JSON.stringify(result));
Need to remove the alert.

2021-01-19 07:02 UTC, indraraj requested changes
UI seems to be breaking on the RuntimeOptions step for Postgres.

2021-01-19 16:41 UTC, mdrillin commented
Amended the commit to fix issues
- removed alert (oops)
- fixed problem in Utils which caused RuntimeStep error
- I also removed alert on DataOptions and RuntimeOptions step, since I was getting duplicate success messages as shown below on those steps:

![DuplicateMsg](https://user-images.githubusercontent.com/1820403/105064781-c4248080-5a42-11eb-90b1-0dd785c6de29.png)

2021-01-20 05:47 UTC, indraraj approved these changes

2021-01-20 05:48 UTC, indraraj commented
Tested locally, Looks good.

2021-01-20 05:48 UTC, merged